# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ae582866d98fb74d8288ea782820ef1dabca506d1e5bcb5ec9462d60bf91246b32df221d15a2c23b3628751026fae4e242844e6ec7c6bed5f70bb118c9757ed5

test:
  secret_key_base: 57f621b6f14130978e8c0dcadb999eabca21aed3b6bbf544950d18575ceb3f35e07223d61e611dbd72a15e2c6c61056ff7d4ed3dd20eb49913de70156f742858

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
